### ISSUE TITLE
bug when parsing object with `.` in key and array as value

### ISSUE THREAD

**Issue by bgotink** [kevin-smets/caml#6]
``` yml
# cat test.yml 
foo:
  'baz.qux':
    - lorem
    - ipsum
```

``` js
// caml -d . -f test
{ foo: { '\'baz': { 'qux\'': [ 'lorem', 'ipsum' ] } } }
```
