### ISSUE TITLE
Inline comments cause loss of properties

### ISSUE THREAD

**Issue by kevin-smets** [kevin-smets/caml#8]
Oriniginally submitted by @asgoth - the sanitise step is too eager. Using comments after a property causes the property to disappear, e.g.

```
path:
  to:
    some: "value" # some explanation what this does
    other: "value"
```

Results in

```
{
  path: {
    to: {
      other: "value"
    }
  }
}
```

Property some is gone.

**Workaround:** Keep your comments on a dedicated line
